### ISSUE TITLE
Capítulo 1 - Diagrama conceptual

### ISSUE THREAD

**Issue by PaulaCuesta** [RodrigoPascual/Ing_Gest_Poyectos#8]

**Comment by RodrigoPascual** [comment]
Hemos decidido hacer dos esquemas, Daniel se encargó de un mapa conceptual estilo árbol y yo, Rodrigo hice un mapa de ideas estilo resumen donde agrupé las ideas principales de los distintos puntos

**Comment by RodrigoPascual** [comment]
Hemos decidido hacer dos esquemas, Daniel se encargó de un mapa conceptual estilo árbol y yo, Rodrigo hice un mapa de ideas estilo resumen donde agrupé las ideas principales de los distintos puntos.
